### ISSUE TITLE
Fedora 35 armhf chroot guide

### ISSUE THREAD

**Issue by mosen** [Wooty-B/LX2K_Guide#4]
Hi @Wooty-B,
I'm running Fedora 35 per your guide on the LX2K, and I noticed that you are running box86 in an armhf chrooted environment.
I wondered if you had that on your radar?

If not, I will document my steps and PR the guide.

**Comment by Wooty-B** [comment]
It was not on my mind, however I am open to contributions and covering more OS's would better help the scope of this guide. Currently my focus has been trying to get Steam running again under an schroot, as well as a barebones chroot and multiarch; currently this eludes me.

Thinking this could get it's own 32-bit support section since it's not just Debian based. looking forward to your contributions and trying them out. Thanks!

**Comment by Wooty-B** [comment]
@mosen Have you written up any support documentation on this? Revisiting, it appears there is still no multilib support in Fedora on the aarch64 platform. I haven't had much time to play with other operating systems and have had this on the backburner for now.

**Comment by mosen** [comment]
I'm still running fedora on LX2K but I haven't revisited this at all lately. Although thanks for reminding me

**Comment by Wooty-B** [comment]
I am going to close this issue for now. As of recently Fedora has depreciated armhf builds and is 64-bit only, meaning to get an up-to-date 32-bit chroot you will need to use a different distro. Moreover, chroot and x86 use-cases are being moved to a dedicated guide located here:

https://github.com/Wooty-B/Project_BoxWine/blob/main/README.md

If you have any more questions on the subject however please feel free to open an issue over on that project page.
